import Head from 'next/head'
//import Image from 'next/image'
//import { Inter } from '@next/font/google'
//import {Link} from 'next/link'
//import styles from '../styles/home.module.css'




import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>Monkey Temple</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
        </div>
      
    </>
  )
}
